create table "public"."article_location_history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "location_id" bigint not null,
    "equipment_id" bigint not null,
    "created_by_user" uuid not null default auth.uid(),
    "gps_coordinates" character varying,
    "gps_accuracy" character varying
);


alter table "public"."article_location_history" enable row level security;

alter table "public"."locations" add column "metadata" jsonb;

CREATE UNIQUE INDEX article_location_history_pkey ON public.article_location_history USING btree (id);

alter table "public"."article_location_history" add constraint "article_location_history_pkey" PRIMARY KEY using index "article_location_history_pkey";

alter table "public"."article_location_history" add constraint "article_location_history_created_by_user_fkey" FOREIGN KEY (created_by_user) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."article_location_history" validate constraint "article_location_history_created_by_user_fkey";

alter table "public"."article_location_history" add constraint "article_location_history_equipment_id_fkey" FOREIGN KEY (equipment_id) REFERENCES equipments(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."article_location_history" validate constraint "article_location_history_equipment_id_fkey";

alter table "public"."article_location_history" add constraint "article_location_history_location_id_fkey" FOREIGN KEY (location_id) REFERENCES locations(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."article_location_history" validate constraint "article_location_history_location_id_fkey";

grant delete on table "public"."article_location_history" to "anon";

grant insert on table "public"."article_location_history" to "anon";

grant references on table "public"."article_location_history" to "anon";

grant select on table "public"."article_location_history" to "anon";

grant trigger on table "public"."article_location_history" to "anon";

grant truncate on table "public"."article_location_history" to "anon";

grant update on table "public"."article_location_history" to "anon";

grant delete on table "public"."article_location_history" to "authenticated";

grant insert on table "public"."article_location_history" to "authenticated";

grant references on table "public"."article_location_history" to "authenticated";

grant select on table "public"."article_location_history" to "authenticated";

grant trigger on table "public"."article_location_history" to "authenticated";

grant truncate on table "public"."article_location_history" to "authenticated";

grant update on table "public"."article_location_history" to "authenticated";

grant delete on table "public"."article_location_history" to "service_role";

grant insert on table "public"."article_location_history" to "service_role";

grant references on table "public"."article_location_history" to "service_role";

grant select on table "public"."article_location_history" to "service_role";

grant trigger on table "public"."article_location_history" to "service_role";

grant truncate on table "public"."article_location_history" to "service_role";

grant update on table "public"."article_location_history" to "service_role";


