name: CI Playwright E2E

on:
  workflow_run:
    workflows: [ "CI Vitest" ]
    types:
      - completed

permissions:
  contents: read

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: "Move config_noseed.toml to supabase/config.toml (if present)"
        run: |
          if [ -f supabase/config_noseed.toml ]; then
            mv supabase/config_noseed.toml supabase/config.toml
          else
            echo "No config_noseed.toml present, skipping"
          fi

      - name: Install dependencies
        run: npm ci

      # Restore Prisma cache
      - name: Cache Prisma engines
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/prisma
            node_modules/.prisma
          key: ${{ runner.os }}-prisma-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-prisma-

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      # Determine Supabase CLI version for cache key stability
      - name: Determine Supabase CLI version
        id: supabase-cli-version
        run: echo "version=$(supabase --version | tr ' ' '-' )" >> $GITHUB_OUTPUT

      # Restore cached Supabase Docker images from prepare job
      - name: Restore Supabase Docker images cache
        id: supabase-images-cache
        uses: actions/cache@v4
        with:
          path: .cache/supabase-images.tar
          key: ${{ runner.os }}-supabase-images-${{ steps.supabase-cli-version.outputs.version }}-${{ hashFiles('supabase/config.toml') }}
          restore-keys: |
            ${{ runner.os }}-supabase-images-${{ steps.supabase-cli-version.outputs.version }}-
            ${{ runner.os }}-supabase-images-

      # Load cached Docker images if available
      - name: Load cached Supabase Docker images
        if: steps.supabase-images-cache.outputs.cache-hit == 'true'
        run: |
          docker load -i .cache/supabase-images.tar

      - name: Start Supabase stack
        run: supabase start

      - name: Export Supabase environment
        run: ./scripts/write-supabase-env.sh > .env.local

      - name: Create symlink for .env
        run: ln -s .env.local .env

      - name: Create Prisma client
        run: npx prisma generate

      # Determine Playwright version and restore cache
      - name: Determine Playwright version
        id: playwright-version
        run: echo version=$(node -e "console.log(require('playwright/package.json').version)") >> $GITHUB_OUTPUT

      # Restore Playwright browsers cache from prepare job
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers (from cache or download)
        run: npx playwright install --with-deps

      - name: Build Next.js app
        run: npm run build

      - name: Start Next.js app and wait for readiness
        run: |
          npm run start > next.log 2>&1 &
          NEXT_PID=$!
          echo "Waiting for Next.js to respond on http://127.0.0.1:3000..."
          for i in $(seq 1 60); do
            if curl -sSf http://127.0.0.1:3000 >/dev/null 2>&1; then
              echo "Next.js is up"
              break
            fi
            echo "Waiting... ($i)"
            sleep 2
          done
          if ! curl -sSf http://127.0.0.1:3000 >/dev/null 2>&1; then
            echo "Next.js failed to start. Printing last 200 lines of next.log:" >&2
            tail -n 200 next.log || true
            kill $NEXT_PID || true
            exit 1
          fi

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:3000
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          if-no-files-found: ignore

      - name: Stop Supabase stack
        if: always()
        run: supabase stop
