name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - name: "Move config_noseed.toml to supabase/config.toml"
        run: mv supabase/config_noseed.toml supabase/config.toml
      - name: Install dependencies
        run: npm ci
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase stack
        run: supabase start

      - name: Export Supabase environment
        run: |
          supabase status -o env | grep '=' > supabase.env
          if [ ! -s supabase.env ]; then
            echo "Supabase env output is empty" >&2
            cat supabase.env
            exit 1
          fi
          set -a
          . supabase.env
          set +a
          {
            echo "NEXT_PUBLIC_SUPABASE_URL=${API_URL}"
            echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}"
            echo "SUPABASE_SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}"
          } >> "$GITHUB_ENV"

      - name: Create env file for Next.js
        run: |
          cat <<EOF > .env.local
          NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
          SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
          EOF
      - name: Create symlink for .env
        run: ln -s .env.local .env

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build Next.js app
        run: npm run build
      - name: Start Next.js app
        run: npm run start &
      - name: Run full test suite (lint, tsc, unit, e2e)
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:3000
          NEXT_PUBLIC_SUPABASE_URL: ${{ env.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ env.SUPABASE_SERVICE_ROLE_KEY }}
        run: npm run test
