name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'
      - name: "Move config_noseed.toml to supabase/config.toml (if present)"
        run: |
          if [ -f supabase/config_noseed.toml ]; then
            mv supabase/config_noseed.toml supabase/config.toml
          else
            echo "No config_noseed.toml present, skipping"
          fi
      - name: Install dependencies
        run: npm ci
      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase stack
        run: supabase start

      - name: Export Supabase environment
        run: ./scripts/write-supabase-env.sh > .env.local

      - name: Create symlink for .env
        run: ln -s .env.local .env

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Build Next.js app
        run: npm run build
      - name: Start Next.js app and wait for readiness
        run: |
          # Start Next.js in background and capture logs
          npm run start > next.log 2>&1 &
          NEXT_PID=$!
          echo "Waiting for Next.js to respond on http://127.0.0.1:3000..."
          for i in $(seq 1 60); do
            if curl -sSf http://127.0.0.1:3000 >/dev/null 2>&1; then
              echo "Next.js is up"
              break
            fi
            echo "Waiting... ($i)"
            sleep 2
          done
          if ! curl -sSf http://127.0.0.1:3000 >/dev/null 2>&1; then
            echo "Next.js failed to start. Printing last 200 lines of next.log:" >&2
            tail -n 200 next.log || true
            kill $NEXT_PID || true
            exit 1
          fi
      - name: Run full test suite (lint, tsc, unit, e2e)
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:3000
          NEXT_PUBLIC_SUPABASE_URL: ${{ env.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ env.SUPABASE_SERVICE_ROLE_KEY }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: npm run test
