name: DEPRECATED - Integration Tests (combined)

on:
  # Manual only to avoid duplicate CI after split workflows
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    runs-on: ubuntu-latest
    if: false # disabled

    steps:
      - run: echo "Deprecated workflow. Use split CI workflows instead."
