name: DEPRECATED - Combined Lint/TS/Unit

on:
  # Manual only to avoid duplicate CI after split workflows
  workflow_dispatch:

permissions:
  contents: read

jobs:
  noop:
    name: Deprecated (do not use)
    runs-on: ubuntu-latest
    if: false # disabled

    steps:
      - run: echo "Deprecated workflow. Use split CI workflows instead."